# heartbeat = 7000  # when task is long, the rabbitmq server will be disconnected if the heartbeat is too short
heartbeat = 0  # when task is long, the rabbitmq server will be disconnected if the heartbeat is too short
channel_max = 2048
consumer_timeout = 31622400000 # when task is long, the new task cannot be added to the queue if the consumer_timeout is too short